---
apiVersion: v1
kind: Pod
metadata:
  name: kafdrop
  labels:
    app: kafdrop
spec:
  containers:
    - name: kafdrop
      image: obsidiandynamics/kafdrop
      ports:
        - containerPort: 9000
      env:
        - name: JVM_OPTS
          value: "-Xms32M -Xmx64M"
        - name: SERVER_SERVLET_CONTEXTPATH
          value: "/"
        - name: SERVER_PORT
          value: "9000"
        - name: KAFKA_BROKERCONNECT
          value: "kafka-cluster-kafka-bootstrap.kafka-cluster.svc:9092"

---
apiVersion: v1
kind: Service
metadata:
  name: kafdrop-service
spec:
  type: NodePort
  selector:
    app: kafdrop
  ports:
    - name: http
      protocol: TCP
      port: 9000
      targetPort: 9000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kafdrop-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
    ingress.kubernetes.io/rewrite-target: "/"
spec:
  rules:
    - http:
        paths:
          - path: /kafdrop
            pathType: Prefix
            backend:
              service:
                name: kafdrop-service
                port:
                  number: 9000