apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elastic
spec:
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  version: 7.12.0
  nodeSets:
  - name: default
    count: 1
    config:
      xpack.security.authc:
        anonymous:
          roles: superuser
          authz_exception: true
      node.store.allow_mmap: false