apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: elastic
spec:
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  version: 7.12.0
  count: 1
  config:
    xpack.security.authc:
      providers:
       anonymous.anonymous1:
         order: 0
         description: "Anonymous access"
         credentials: "elasticsearch_anonymous_user"
  elasticsearchRef:
    name: elastic
  podTemplate:
    spec:
      containers:
        - name: kibana
          readinessProbe:
            tcpSocket:
              port: 5601
            initialDelaySeconds: 25
            periodSeconds: 10