apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: elastic
spec:
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  version: 7.12.0
  count: 1
  config:
    xpack.security.authc:
      providers:
       anonymous.anonymous1:
         order: 0
         description: "Anonymous access"
         credentials: "elasticsearch_anonymous_user"
  elasticsearchRef:
    name: elastic
  podTemplate:
    spec:
      containers:
        - name: kibana
          readinessProbe:
            tcpSocket:
              port: 5601
            initialDelaySeconds: 25
            periodSeconds: 10
          env:
            - name: SERVER_BASEPATH
              value: "/kibana"

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: elastic-kb-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
    - http:
        paths:
          - path: /kibana
            pathType: Prefix
            backend:
              service:
                name: elastic-kb-http
                port:
                  number: 5601