apiVersion: v1
kind: Pod
metadata:
  name: kafdrop
  labels:
    app: kafdrop
spec:
  containers:
    - name: kafdrop
      image: obsidiandynamics/kafdrop
      ports:
        - containerPort: 9000
      env:
        - name: JVM_OPTS
          value: "-Xms32M -Xmx64M"
        - name: SERVER_SERVLET_CONTEXTPATH
          value: "/kafdrop"
        - name: SERVER_PORT
          value: "9000"
        - name: KAFKA_BROKERCONNECT
          value: "kafka-cluster-kafka-bootstrap.kafka-cluster.svc:9092"