apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: parsed-jobs
  labels:
    strimzi.io/cluster: kafka-cluster
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  partitions: 1
  replicas: 1