apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: mongodb-source
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    strimzi.io/cluster: my-connect
spec:
  class: com.mongodb.kafka.connect.MongoSourceConnector
  tasksMax: 1
  config:
    connection.uri: "mongodb://my-user:testabc@mongodb-db-svc.mongo.svc:27017"
    database: jobs
    copy.existing: true
    key.converter": "org.apache.kafka.connect.json.JsonConverter"
    key.converter.schemas.enable: false
    value.converter: "org.apache.kafka.connect.json.JsonConverter"
    value.converter.schemas.enable: false
    topic.namespace.map: '{"*": "jobs"}'