apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: elasticsearch-sink
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    strimzi.io/cluster: my-connect
spec:
  class: io.confluent.connect.elasticsearch.ElasticsearchSinkConnector
  tasksMax: 1
  config:
    connection.url: "http://elastic-es-http.es-stack.svc:9200"
    topics: parsed-jobs
    value.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter.schemas.enable: false
    schema.ignore: true