apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: my-connect
  annotations:
    strimzi.io/use-connector-resources: "true"
    argocd.argoproj.io/sync-wave: "0"
spec:
  replicas: 1
  bootstrapServers: kafka-cluster-kafka-bootstrap:9092
  config:
    group.id: my-connect
    offset.storage.topic: my-connect-offsets
    config.storage.topic: my-connect-configs
    status.storage.topic: my-connect-status
    config.storage.replication.factor: 1
    offset.storage.replication.factor: 1
    status.storage.replication.factor: 1
    key.converter: "org.apache.kafka.connect.json.JsonConverter"
    value.converter: "org.apache.kafka.connect.json.JsonConverter"
    key.converter.schemas.enable: "false"
    value.converter.schemas.enable: "false"
  image: angiakfir/kafka-connect-build
  # build:
  #   output:
  #     type: docker
  #     image: angiakfir/kafka-connect-build
  #     pushSecret: myregistrykey
  #   plugins:
  #     - name: es-sink-connector
  #       artifacts:
  #         - type: jar
  #           url: "https://github.com/aphan1um/jobsys/raw/master/kafka-plugins/elasticsearch-kafka-connect-11.0.4-all.jar"
  #     - name: mongodb-connector
  #       artifacts:
  #         - type: jar
  #           url: "https://github.com/aphan1um/jobsys/raw/master/kafka-plugins/mongo-kafka-1.5.0-all.jar"
  template:
    pod:
      imagePullSecrets:
        - name: myregistrykey
  resources:
    requests:
      cpu: "1"
      memory: 2Gi
    limits:
      cpu: "2"
      memory: 2Gi
  jvmOptions:
    "-Xmx": "512m"
    "-Xms": "512m"